---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-user
  namespace: sarafu-production
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developer-full-access
  namespace: sarafu-production
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: developer-role-binding
  namespace: sarafu-production
subjects:
  - kind: ServiceAccount
    name: developer-user
    namespace: sarafu-production
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-full-access
