apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app

  # Pod template
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: aws-ecr
      containers:
        - name: app
          image: 847108109661.dkr.ecr.eu-central-1.amazonaws.com/cic-platform:server_83ebbe85d92ff405ec85e0ad2f10d5716615fe83
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: "0.5"
              memory: 256Mi
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: app
          ports:
            - containerPort: 3031
---
apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    run: app
spec:
  ports:
    - port: 3031
      protocol: TCP
  selector:
    run: app
